### ISSUE TITLE
🖹 [content] - What we do - initial content

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/rht-labs.github.io#12]
Add first commit of content for 'what we do' content focussed on
- What we do with customers - e.g. Residencies and other products
- What we do internally at Red Hat

**Comment by kattekrab** [comment]
Initial content is done. No?
If yes, can we close this? If no - what else do we need / desire here?

**Comment by kattekrab** [comment]
I see it's in "done" in the project, let's close this.
