### ISSUE TITLE
🖹 [content] - How does Labs use OPL

### ISSUE THREAD

**Issue by mtakane** [rht-labs/rht-labs.github.io#19]
Add initial commit about a supporting practice of OPL as one thing that we leverage at Labs to support our ability to deliver.

**Comment by kattekrab** [comment]
I've renamed "How roil works" to "How we work", replaced Lorem Ipsum with a stub about being team first, and that we use OPL. 

See PR #30

**Comment by kattekrab** [comment]
Initial stub for this is here: https://rht-labs.com/docs/how-we-work.html

![image](https://user-images.githubusercontent.com/172755/153326079-332fac10-e7dd-40c1-bf16-857e7d7905d2.png)

[Open Practice Library](https://openpracticelibrary.com/)
We both draw inspiration from, and contribute to the Open Practice Library.

The Open Practice Library is an open source, community-driven inspired library of best practices and tools. It helps individuals, teams and entire businesses figure out the optimal ways to get to the best outcome.

**Comment by kattekrab** [comment]
What else do we want here?
@mtakane ? @mwalker5000 ?
