### ISSUE TITLE
🖹 [content] - Create a contribution guide

### ISSUE THREAD

**Issue by mwalker5000** [rht-labs/rht-labs.github.io#41]
Make it clear how people can contribute content, with a step-by-step process, similar to our build guide.

Document (or create a placeholder) for the team responsible for reviewing PRs and committing code to production.

Mention that all work should be represented as issues as a best practice (don't just create cards in the kanban project please)

**Comment by eformat** [comment]
https://github.com/rht-labs/rht-labs.github.io/pull/46

**Comment by eformat** [comment]
closing this. initial contrib guide started and pushed

https://rht-labs.com/docs/contribution-guide.html
