### ISSUE TITLE
Fix the 'how labs works' link

### ISSUE THREAD

**Issue by mwalker5000** [rht-labs/rht-labs.github.io#42]
https://rht-labs.com/docs/how-roil-works.html

is hitting a 404

**Comment by kattekrab** [comment]
This is my fault.  I renamed how-roil-works to how-we-work, to follow our guide line to never call ourselves oil or roil or rhoil.  

This means updating _data/docs.yml and _docs/index.md to point to that file name instead.

Fixing now.

**Comment by kattekrab** [comment]
Although I can't assign myself!

**Comment by kattekrab** [comment]
Fixed! (I think)
To the best of my knowledge - that link lives in 4 places.
✅  1. The home page. docs/index.md
✅  2. The nav. data/docs.yml
✅  3. Previous page docs/what-is-rh-open-innovation-labs.md
❌ 4. Following page docs/labs-principles.md

ok - still one more to fix.  Coming up!

**Comment by kattekrab** [comment]
✅  4. Following page docs/labs-principles.md

And done! Thanks @eformat 
@mwalker5000 - that should do the trick.
