### ISSUE TITLE
Create backlink to redhat.com web site 

### ISSUE THREAD

**Issue by oybed** [rht-labs/rht-labs.github.io#43]
The new site should link back to the official Labs Red Hat site: https://www.redhat.com/en/services/consulting/open-innovation-labs

**Comment by eformat** [comment]
FYI ... On the "Stories" page .. i did link back to this site when you click "Talk to Us" 

![Screenshot from 2022-02-10 14-07-18](https://user-images.githubusercontent.com/712608/153335270-0e327d49-d5bb-4969-b10f-c34f40f43c71.png)

We could move this up to the main site for example
